@startuml

Clase01 <|-- Clase02
Clase03 *-- Clase04
Clase05 o-- Clase06
Clase07 -- Clase08
Clase09 .. Clase10
interface Interface11
Interface11 <|.. Clase12 
abstract class Clase12
Clase12 <|-- Clase13

Clase01 : + operacion01()
Clase01 : ~ operacion01.1()

Clase01 : - attribute01 
Clase01 : {static} operacion_de_clase()

Clase03 : # Clase04[]  parte01

Interface11 : method01()
Interface11 : method02()

Clase12 : {abstract} method01()
Clase12 : method02()

@enduml